on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Which package to bundle'
        required: true
      overwrite:
        description: 'Overwrite existing bundles'
        type: boolean
        required: false
        default: false

name: Create Windows bundles

jobs:
  Bundler:
    runs-on: windows-latest
    name: Bundle ${{ github.event.inputs.package }}
    steps:
      - name: Prepare git
        run: |
          git config --global core.autocrlf false
          git config --global user.email 'm.sepulveda@mail.utoronto.ca'
          git config --global user.name  'Mauricio Pacha Vargas Sepulveda'

      - uses: msys2/setup-msys2@v2
        update: true
        install: |
          mingw-w64-ucrt-x86_64-toolchain
          mingw-w64-clang-x86_64-toolchain
          mingw-w64-clang-aarch64-toolchain

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: bundle
        name: Create bundle
        shell: msys2 {0}
        run: ./build.sh
        env:
          package: ${{ github.event.inputs.package }}
          overwrite: ${{ github.event.inputs.overwrite }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.package }}-${{ steps.bundle.outputs.version }}
          files: dist/*.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
