name: Build and Release Tesseract with R 4.4

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Build tesseract for R 4.4'
        required: true
      overwrite:
        description: 'Overwrite existing bundles'
        type: boolean
        required: false
        default: false

jobs:
  Bundler:
    runs-on: windows-latest
    name: Bundle ${{ github.event.inputs.package }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare git
        run: |
          git config --global core.autocrlf false
          git config --global user.email 'm.sepulveda@mail.utoronto.ca'
          git config --global user.name  'Mauricio Pacha Vargas Sepulveda'

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-autotools
            mingw-w64-x86_64-leptonica
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-libtiff
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-giflib
            mingw-w64-x86_64-libwebp
            mingw-w64-x86_64-openjpeg2

      - name: Create CRAN-compliant redirections
        shell: msys2 {0}
        run: |
          mkdir -p build
          cat > build/r_redirects.h << 'EOF'
          #ifndef R_REDIRECTS_H
          #define R_REDIRECTS_H

          #include <cstdlib>
          #include <string>
          #include <iostream>
          #include <streambuf>
          #include <random>

          // Custom stream buffer that silently discards output
          class NullStreambuf : public std::streambuf {
          protected:
            virtual int overflow(int c) override { return c; }
            virtual std::streamsize xsputn(const char*, std::streamsize n) override { return n; }
          public:
            static NullStreambuf& instance() {
              static NullStreambuf instance;
              return instance;
            }
          };

          // Safe random number generator
          std::mt19937 safe_random_generator(0);
          std::uniform_int_distribution<int> safe_random_dist(0, RAND_MAX);

          // Function replacements
          extern "C" {
            // Empty abort implementation
            void abort(void) { }
            
            // Empty exit implementation
            void exit(int status) { }
            
            // Safe random generator
            int rand(void) { return safe_random_dist(safe_random_generator); }
            
            // Safe random seed
            void srand(unsigned int seed) { safe_random_generator.seed(seed); }
          }

          // Replace cout and cerr with safe versions
          namespace std {
            std::ostream safe_cout(&NullStreambuf::instance());
            std::ostream safe_cerr(&NullStreambuf::instance());
          }

          #define cout std::safe_cout
          #define cerr std::safe_cerr

          #endif // R_REDIRECTS_H
          EOF

      - name: Download Tesseract source
        shell: msys2 {0}
        run: |
          cd build
          git clone https://github.com/tesseract-ocr/tesseract.git
          cd tesseract
          git checkout 5.3.3

      - name: Apply CRAN-compliant modifications
        shell: msys2 {0}
        run: |
          cd build/tesseract
          
          # Copy redirection header to source
          cp ../r_redirects.h src/ccutil/
          
          # Insert include at the top of an early-loaded header
          sed -i '1i#include "r_redirects.h"' src/ccutil/platform.h
          
          # Run autoconf
          ./autogen.sh

      - name: Build Tesseract with CRAN-compliant flags
        shell: msys2 {0}
        run: |
          # Create install directory
          mkdir -p build/install/lib build/install/include build/install/share
          
          # Build with visibility flags and CRAN-compliant settings
          cd build/tesseract
          ./configure --prefix=$GITHUB_WORKSPACE/build/install \
                      --disable-shared \
                      --enable-static \
                      --disable-openmp \
                      CXXFLAGS="-fvisibility=hidden -fvisibility-inlines-hidden -DUSE_STD_NAMESPACE" \
                      CFLAGS="-fvisibility=hidden"
          
          make -j4
          make install

      - name: Download language data
        shell: msys2 {0}
        run: |
          mkdir -p build/install/share/tessdata
          cd build/install/share/tessdata
          
          # Download English and orientation detection data
          curl -L -o eng.traineddata https://github.com/tesseract-ocr/tessdata_best/raw/main/eng.traineddata
          curl -L -o osd.traineddata https://github.com/tesseract-ocr/tessdata_best/raw/main/osd.traineddata

      - name: Package Tesseract
        shell: msys2 {0}
        run: |
          mkdir -p dist
          cd build
          
          # Create package
          tar -czvf ../dist/tesseract-oldR-5.3.5.tar.gz install/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: tesseract-oldR-5.3.5
          name: Tesseract with R 4.4
          draft: false
          prerelease: false
          files: dist/tesseract-oldR-5.3.5.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          