name: Build and Release Tesseract with R 4.4

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Build tesseract for R 4.4'
        required: true
      overwrite:
        description: 'Overwrite existing bundles'
        type: boolean
        required: false
        default: false

jobs:
  Bundler:
    runs-on: windows-latest
    name: Bundle ${{ github.event.inputs.package }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare git
        run: |
          git config --global core.autocrlf false
          git config --global user.email 'm.sepulveda@mail.utoronto.ca'
          git config --global user.name  'Mauricio Pacha Vargas Sepulveda'

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-leptonica
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-libtiff

      - name: Download Tesseract source
        shell: msys2 {0}
        run: |
          git clone https://github.com/tesseract-ocr/tesseract.git
          cd tesseract
          git checkout 4.1.0

      - name: Build Tesseract with CRAN-compliant flags
        shell: msys2 {0}
        run: |
          cd tesseract
          ./autogen.sh
          ./configure
          make
          make install

      - name: Package Tesseract
        shell: msys2 {0}
        run: |
          tar -czvf tesseract-oldR-5.3.5.tar.gz /usr/local/bin/tesseract /usr/local/share/tessdata

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: tesseract-oldR-5.3.5
          release_name: Tesseract with R 4.4
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tesseract-oldR-5.3.5.tar.gz
          asset_name: tesseract-oldR-5.3.5.tar.gz
          asset_content_type: application/gzip
        